import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, GraduationCap, ShieldCheck, Users } from 'lucide-react';

export default function Home() {
  return <main className="home"><nav className="home-nav"><Link className="brand" to="/"><span className="brand-mark"><GraduationCap size={20}/></span>StudentSphere</Link><div className="nav-links"><a href="#modules">Modules</a><Link to="/login">Student login</Link><Link className="btn-primary" to="/admin">Admin login</Link></div></nav>
    <section className="home-hero"><div><p className="eyebrow">Student Management System</p><h1>One clear place for every student journey.</h1><p className="hero-copy">StudentSphere brings student profiles, academic records, and administration into one easy-to-use portal. It replaces manual work with a simple, secure digital experience.</p><div className="hero-actions"><Link className="btn-primary" to="/register">Create student account</Link><Link className="btn-secondary" to="/login">Student sign in</Link></div></div><aside className="hero-card"><small>YOUR CAMPUS AT A GLANCE</small><h3>Organised. Secure. Ready.</h3><div className="mini-list"><div className="mini-row"><span>Student profiles</span><strong>01</strong></div><div className="mini-row"><span>Academic records</span><strong>02</strong></div><div className="mini-row"><span>Admin management</span><strong>03</strong></div></div></aside></section>
    <section id="modules" className="home-section"><div className="section-heading"><p className="eyebrow">Three focused modules</p><h2>Built for the people who use it every day.</h2><p>Each module has a clear responsibility, keeping the system straightforward for students, teachers, and administrators.</p></div><div className="feature-grid"><article className="feature glass-panel"><div className="feature-icon"><ShieldCheck size={22}/></div><h3>Admin module</h3><p>Administrators securely manage student records, update information, and oversee the system.</p></article><article className="feature glass-panel"><div className="feature-icon"><GraduationCap size={22}/></div><h3>Student module</h3><p>Students register once, sign in safely, and view their own academic profile at any time.</p></article><article className="feature glass-panel"><div className="feature-icon"><BookOpen size={22}/></div><h3>Teacher module</h3><p>Teachers can access student records to support academic monitoring and guidance.</p></article></div></section>
    <section className="home-section" style={{paddingTop:0}}><div className="section-heading"><p className="eyebrow">How it works</p><h2>A simple workflow from registration to administration.</h2></div><div className="feature-grid"><article className="feature glass-panel"><div className="feature-icon">1</div><h3>Register</h3><p>A student creates one account with their personal and academic details. Their record is saved securely in the student database.</p></article><article className="feature glass-panel"><div className="feature-icon">2</div><h3>Login and view profile</h3><p>Students sign in at the student login page and can view their own registered details. Administrators use their separate admin login.</p></article><article className="feature glass-panel"><div className="feature-icon">3</div><h3>Manage records</h3><p>Admins use the dashboard to add, update, and delete student records while teachers can view student information.</p></article></div></section>
    <section className="home-section" style={{paddingTop:0}}><div className="glass-panel" style={{padding:'32px',display:'flex',justifyContent:'space-between',gap:'24px',alignItems:'center',flexWrap:'wrap'}}><div><p className="eyebrow">Get started</p><h2 style={{marginBottom:0,color:'var(--navy)'}}>Ready to manage student information better?</h2></div><Link className="btn-primary" to="/register"><Users size={18}/> Register as a student</Link></div></section><footer className="home-footer">© 2026 StudentSphere · Student Management System</footer></main>;
}
